FROM node:18.17.1

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ./src ./src
COPY ./public ./public

#Trigger

CMD npx wait-port metadata:80 && \
    npx wait-port history:80 && \
    npm start